[package]
name = "rustyboy-web-client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
debug-overlay = []

[dependencies]
rustyboy-core = { path = "../../../core" }
font8x8 = "0.3"
js-sys = "0.3"
ratatui = { version = "0.30", default-features = false }
wasm-bindgen = "0.2"
